name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'zulu'
      - name: Install Docker 
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - run: |
          set -x
          docker version
          docker run --rm hello-world
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.6.0      
      - name: Build with Maven
        #run: mvn --batch-mode --update-snapshots package
        run: mvn clean install
      - name: Build image
        run: docker build --build-arg JAR_FILE=target/*.jar -t myorg/myapp .
